---
title: Learn about basic Javascript for Automation
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: minhazq@gmail.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
